### PR TITLE
Add simple script to test the tsdfx process.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by dag-erling** [comment]
How about integrating your test script (minus the configure bit) as an automake test, and using the [gnulib valgrind-tests module](https://www.gnu.org/software/gnulib/manual/html_node/Running-self_002dtests-under-valgrind.html) or something similar instead?

**Comment by petterreinholdtsen** [comment]
Would be great! :)  But until that happen, I use that simple test script to ensure tsdfx is not completely broken. :)

**Comment by dag-erling** [comment]
See #14 instead, which integrates the test script into the build framework.

**Comment by petterreinholdtsen** [comment]
Dropped because of a better approach in #14.

**Pull request closed without merging**
