### PR TITLE
Avoid C99/C++ style variable declaration.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
This make the code buildable also with C90 compilers.

### CODE REVIEW

**Comment by dag-erling** [comment]
How many C90 compilers have you encountered recently?

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> How many C90 compilers have you encountered recently?

## One. :)

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
[Petter Reinholdtsen]

> [Dag-Erling Smørgrav]
> 
> > How many C90 compilers have you encountered recently?
> 
> One. :)

No, seriously. How many platforms have you encountered recently where tsdfx would be useful but a C99 or better compiler is not available?

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> No, seriously. How many platforms have you encountered recently where
> tsdfx would be useful but a C99 or better compiler is not available?

This is how I encountered it, on my laptop running Debian Jessie:

make[2]: Entering directory '/home/pere/usit/tsdfx/lib/libtsd'
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../include  -I../../include   -g -O2 -Wall -Wextra -Wcast-qual -Wshadow -MT tsd_sha1.lo -MD -MP -MF .deps/tsd_sha1.Tpo -c -o tsd_sha1.lo tsd_sha1.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../include -I../../include -g -O2 -Wall -Wextra -Wcast-qual -Wshadow -MT tsd_sha1.lo -MD -MP -MF .deps/tsd_sha1.Tpo -c tsd_sha1.c  -fPIC -DPIC -o .libs/tsd_sha1.o
tsd_sha1.c: In function 'sha1_compute':
tsd_sha1.c:86:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < 16; ++i)
  ^
tsd_sha1.c:86:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
tsd_sha1.c:88:11: error: redefinition of 'i'
  for (int i = 16; i < 80; ++i) {
           ^
tsd_sha1.c:86:11: note: previous definition of 'i' was here
  for (int i = 0; i < 16; ++i)
           ^
tsd_sha1.c:88:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 16; i < 80; ++i) {
  ^
tsd_sha1.c: In function 'tsd_sha1_final':
tsd_sha1.c:233:2: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  for (int i = 0; i < 5; ++i)
  ^
Makefile:444: recipe for target 'tsd_sha1.lo' failed
make[2]: **\* [tsd_sha1.lo] Error 1
make[2]: Leaving directory '/home/pere/usit/tsdfx/lib/libtsd'
Makefile:347: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/pere/usit/tsdfx/lib'
Makefile:377: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1
pere@minerva:~/usit/tsdfx$ gcc --version
gcc-4.9.real (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

pere@minerva:~/usit/tsdfx$

I could have solved it by adding -std=c99 using configure.in, but as the
change was so non-intrusive to make it portable to older compilers, I

## decided for that approach instead.

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
That's a bug in either Debian's toolchain or autoconf. `AC_PROG_CC_STDC` is supposed to enforce C99 or newer, and gcc is supposed to default to `gnu99`. Try replacing `AC_PROG_CC_STDC` with `AC_PROG_CC_C99`. The code will never build in a true C90 environment anyway; what you saw was a C99 compiler trying to enforce C90 syntax in a C99 environment (and failing, since it did not complain about C++-style comments).

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> That's a bug in either Debian's toolchain or
> autoconf. `AC_PROG_CC_STDC` is supposed to enforce C99 or newer, and
> gcc is supposed to default to `gnu99`. Try replacing `AC_PROG_CC_C99`
> with `AC_PROG_CC_C99`. The code will never build in a true C90
> environment anyway; what you saw was a C99 compiler trying to enforce
> C90 syntax in a C99 environment (and failing, since it did not
> complain about C++-style comments).

I found the cause for my confusion.  It was me doing configure in an
environment with gcc 6.2.0 (my unstable chroot), and then doing 'make
clean all' in my normal development environment.  This caused autoconf
to drop the -std=gnu99 option, required to get the code building.
Rerunning configure solved it.

## 

Happy hacking
Petter Reinholdtsen

**Pull request closed without merging**
