### PR TITLE
Raise scan limit from 40000 to 80000.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
This reduce the chance of blocking a project with many form submissions from
importing any files.

Related to UiO RT #2317407, 2854030 and pull request #123.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
I tested how long it took to scan 67000 files via nfs, and it was done in approximately 22 seconds.  This make me believe we could handle the raised maximum.

**Comment by petterreinholdtsen** [comment]
The build failures with clang and gcc are fixed in pull request #130 and #131.

**Comment by dag-erling** [comment]
1. Please submit working code only.
2. This should be parametrized, preferably in a configuration file, but a command-line switch works too.

**Comment by petterreinholdtsen** [comment]
While I agree that it should be parameterized, we are on a tight deadline to fix a fatal problem in production and need to increase the limit very soon.

**Pull request merged**
