### PR TITLE
Log an error if source and destination offset do not match.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**

### CODE REVIEW

**Comment by dag-erling** [comment]
I would prefer an assert() at the top of copyfile_copy(). I already have a patch for that locally.

**Comment by petterreinholdtsen** [comment]
How come?  I considered the assert() approach, and concluded I would like to have a specific log message in the syslog instead.  As far as I could tell, assert() failures would not make it to syslog.

**Comment by dag-erling** [comment]
An error message would be appropriate if this was something that could occur in normal operation—due to invalid input, for instance. But this is actually a “can't happen” situation which can only occur as a result of a bug somewhere else in the code. If it does, `assert()` will raise `SIGABRT` which is logged by the kernel, at least on *BSD. If you want it in the tsdfx log specifically, we can change `tsd_task_poll()` to log an error if the child exited due to a signal. Come to think of it, we should do that anyway.

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> An error message would be appropriate if this was something that could
> occur in normal operation—due to invalid input, for instance. But this
> is actually a “can't happen” situation which can only occur as a
> result of a bug somewhere else in the code. If it does, `assert()`
> will raise `SIGABRT` which is logged by the kernel, at least on
> *BSD. If you want it in the tsdfx log specifically, we can change
> `tsd_task_poll()` to log an error if the child exited due to a
> signal. Come to think of it, we should do that anyway.

Yes.  But I also want to know the files involved.  What is the best way
to get the file names out?  I guess I also should print the offset
values, to have more information when trying to debug this issue.

## 

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
Pull requests #35 and #36 together should do what you wanted.

**Comment by petterreinholdtsen** [comment]
[Dag-Erling Smørgrav]

> Pull requests #35 and #36 together should do what you wanted.

I tested after applying both, and the log message I get is this:

  2015-11-11 14:25:30 UTC [5235] warning: tsd_task.c:450 tsd_task_poll()
    7e0f613765531f94c15d0d82846966097df6d090 [5262] caught signal 6

Not quite what I had in mind, as the filename is missing and there is no
explanation exactly what went wrong (probably an assert, but do not know
which assert).

I can grep for the pid to figure out which files were involved, but have
no way to figure out which assert() triggered:

  2015-11-11 14:25:30 UTC [5262] verbose: copier.c:419 tsdfx_copier()
    /home/pere/usit/tsdfx/t/t5229/src/test2 to
    /home/pere/usit/tsdfx/t/t5229/dst/test2

  2015-11-11 14:25:30 UTC [5262] notice: copier.c:160 copyfile_open()
    created file /home/pere/usit/tsdfx/t/t5229/dst/test2 

  2015-11-11 14:25:30 UTC [5235] warning: tsd_task.c:450 tsd_task_poll()
    7e0f613765531f94c15d0d82846966097df6d090 [5262] caught signal 6

## 

Happy hacking
Petter Reinholdtsen

**Comment by dag-erling** [comment]
In that case, we can add our own `ASSERT()` macro to `log.h` (or a separate `assert.h`) and use that instead of `assert()`.

**Comment by petterreinholdtsen** [comment]
This was fixed in a different way.  Closing.

**Pull request closed without merging**
