### PR TITLE
Include invalid file name in log messages.

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
When a file with invalid characters is encountered, make sure the
log entry contain the full file name.  Also, explain in the log
entry what the inode number is.

### CODE REVIEW

**Comment by dag-erling** [comment]
The reason why the file name was rejected is that we considered it unsafe to log. If we're going to start logging rejected file names, we should percent-encode them.

**Comment by petterreinholdtsen** [comment]
I rewrote the patch to percent encode the file names.  Better now?

**Comment by dag-erling** [comment]
Yes. You should use the `percent_enclen()` macro instead of just multiplying by three, though (even if that's exactly what `percent_enclen()` does...). Plenty of style bugs as well, but we can deal with them later.

**Comment by petterreinholdtsen** [comment]
Third version in place, using percent_enclen() and size_t.

**Pull request merged**
